version: '3.8'

services:
  app:
    build: .
    container_name: songwriter-id-app
    volumes:
      - .:/app
      - audio_data:/audio_data
      - ./data:/app/data
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://songwriter:password@db:5432/songwriter_db
      - MUSICBRAINZ_API_KEY=${MUSICBRAINZ_API_KEY:-}
      - ACOUSTID_API_KEY=${ACOUSTID_API_KEY:-}
      - ASCAP_API_KEY=${ASCAP_API_KEY:-}
      - BMI_API_KEY=${BMI_API_KEY:-}
    ports:
      - "5001:5000"
    networks:
      - songwriter-network
    # Run in daemon mode with job scheduler
    command: python -m songwriter_id --daemon --jobs-dir=/app/data/jobs
    restart: on-failure

  db:
    image: postgres:14-alpine
    container_name: songwriter-id-db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=songwriter
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=songwriter_db
    ports:
      - "5433:5432"
    networks:
      - songwriter-network
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U songwriter -d songwriter_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  review-ui:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: songwriter-id-ui
    volumes:
      - .:/app
      - ./data:/app/data
    depends_on:
      db:
        condition: service_healthy
      app:
        condition: service_started
    environment:
      - DATABASE_URL=postgresql://songwriter:password@db:5432/songwriter_db
      - FLASK_APP=songwriter_id.review_interface
      - FLASK_ENV=development
      - SECRET_KEY=dev_key_change_in_production
      - JOB_SCHEDULER_DIR=/app/data/jobs
    ports:
      - "8080:5000"
    networks:
      - songwriter-network
    command: flask --app songwriter_id.review_interface run --host=0.0.0.0
    restart: on-failure

networks:
  songwriter-network:
    driver: bridge

volumes:
  postgres_data:
  audio_data:
