# Pipeline Configuration

# General settings
batch_size: 100
log_level: INFO

# Field mapping for catalog import
field_mapping:
  # Standard fields
  title: title
  track_title: title
  track name: title
  name: title
  
  artist: artist_name
  artist_name: artist_name
  artist name: artist_name
  performer: artist_name
  
  album: release_title
  release: release_title
  release_title: release_title
  release title: release_title
  album_title: release_title
  album title: release_title
  
  duration: duration
  length: duration
  time: duration
  
  file: audio_path
  path: audio_path
  audio: audio_path
  audio_path: audio_path
  audio path: audio_path
  file_path: audio_path
  file path: audio_path

# Confidence score thresholds
confidence_thresholds:
  high: 0.75  # Accept results with confidence >= 0.75
  medium: 0.4  # Accept with warning 0.4 <= confidence < 0.75
  low: 0.0    # Send for manual review confidence < 0.4

# API configuration
apis:
  musicbrainz:
    enabled: true
    # Choose the client type: "api" or "database"
    client_type: "database"
    
    # API client settings (used if client_type is "api")
    api:
      enabled: true
      user_agent: "SongwriterCreditsIdentifier/1.0"
      version: "1.0"
      contact: "contact@example.com"
      rate_limit: 1.0  # Requests per second
      retries: 3
    
    # Database client settings (used if client_type is "database")
    database:
      enabled: true
      # Connection string for the MusicBrainz database
      # Use host.docker.internal instead of localhost to access the host machine from Docker
      connection_string: "postgresql://musicbrainz:musicbrainz@host.docker.internal:5434/musicbrainz_db"
      # Connection pool settings
      pool_size: 10
      max_overflow: 20
  
  acoustid:
    enabled: true
    api_key: "YOUR_ACOUSTID_API_KEY"  # Replace with actual key
    rate_limit: 3.0  # Requests per second
    retries: 3
  
  ascap:
    enabled: false
    api_key: ""
    rate_limit: 1.0
  
  bmi:
    enabled: false
    api_key: ""
    rate_limit: 1.0
  
  sesac:
    enabled: false
    api_key: ""
    rate_limit: 1.0

# Tier-specific settings
tier1:
  enabled: true
  sources:
    - musicbrainz
    - ascap
    - bmi
    - sesac
  confidence_threshold: 0.7
  match_strategy: best  # 'best' or 'all' (best = highest confidence match, all = all matches above threshold)
  max_results: 3  # Maximum number of results to process per source

tier2:
  enabled: true
  fuzzy_match_threshold: 0.85
  entity_resolution_threshold: 0.75
  sources:
    - musicbrainz_fuzzy
    - ml_prediction
  confidence_threshold: 0.5

tier3:
  enabled: true
  sources:
    - acoustid
  confidence_threshold: 0.6